
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dev_serviceauto

test:
  <<: *default
  database: test_serviceauto

production:
  <<: *default
  database: prod_serviceauto
